  language: 'php'
  php: 
    - '7.3'
  cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.php-cs-fixer

  before_install: true

  install:
    - composer install

  before_script: true

  script:
      - phpunit tests
      - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

  after_script: true

