  language: 'php'
  php: 
    - '7.3'
  
  before_install: true

  install:
    - composer install
    - composer require friendsofphp/php-cs-fixer

  before_script: true

  script:
      - phpunit tests

  after_script: true
