  language: 'php'
  php: 
    - '7.3'
  
  before_install: true

  install:
    - composer install

  before_script: true

  script:
      - phpunit tests
      - ./vendor/bin/php-cs-fixer --dry-run --diff

  after_script: true
