version: 1

update_configs:
  - package_manager: "php:composer"
    directory: "/composer/helpers"
    update_schedule: "live"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "live"